---
kind: pipeline
name: run_tests
type: docker

steps:
  - name: seed
    image: postgres:15-alpine
    commands:
      - psql -h localhost -U test < ./database/seed/1.create_types.sql
      - psql -h localhost -U test < ./database/seed/2.struct.sql

  - name: test
    image: golang:1.19
    commands:
      - go test ./...

services:
  # This database stays running during the whole pipeline and can be accessed from any of the
  # other steps.
  - name: lymantria_test
    image: postgres:15-alpine
    ports:
    - 5432
    environment:
      POSTGRES_DB: lymantria_test
      POSTGRES_PASSWORD: test-pass
      POSTGRES_USER: test

trigger:
  branch:
    - main

---
kind: pipeline
name: deploy
type: ssh

depends_on:
  - run_tests

server:
  host:
    from_secret: ssh_host
  user:
    from_secret: ssh_username
  ssh_key: 
    from_secret: ssh_key

steps:
  - name: deploy
    commands:
      - cd /home/docker/lymantria-api
      - git pull --rebase
      - docker-compose up -d
